# Generated by Django 3.2.6 on 2021-09-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ftp_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_pure_db', models.BooleanField(verbose_name='enable_pure_db')),
                ('enable_pam', models.BooleanField(verbose_name='enable_pam')),
                ('enable_ssl_cert', models.BooleanField(verbose_name='enable_ssl_cert')),
                ('enable_verbose_log', models.BooleanField(verbose_name='enable_verbose_log')),
                ('enable_no_anonymous', models.BooleanField(verbose_name='enable_no_anonymous')),
                ('ssl_cert_path', models.CharField(max_length=50, verbose_name='ssl_cert_path')),
                ('tls', models.SmallIntegerField(verbose_name='tls')),
                ('tls_chiper_suite', models.CharField(max_length=50, verbose_name='tls_chiper_suite')),
                ('supported_items', models.CharField(choices=[('0', 'ftp'), ('1', 'authpriv'), ('2', 'deamon'), ('3', 'auth'), ('4', 'security'), ('5', 'user'), ('6', 'local'), ('None', 'None')], max_length=9, verbose_name='supported_items')),
                ('syslog_facility_type', models.CharField(choices=[('0', 'ftp'), ('1', 'authpriv'), ('2', 'deamon'), ('3', 'auth'), ('4', 'security'), ('5', 'user'), ('6', 'local'), ('None', 'None')], max_length=9, verbose_name='syslog_facility_type')),
                ('pure_ftp_base_path', models.CharField(max_length=30, verbose_name='pure_ftp_base_path')),
                ('pure_ftp_config_file', models.CharField(max_length=30, verbose_name='pure_ftp_config_file')),
                ('max_clients_number', models.SmallIntegerField(verbose_name='max_clients_number')),
                ('max_clients_per_ip', models.SmallIntegerField(verbose_name='max_clients_per_ip')),
            ],
        ),
    ]
