# Generated by Django 3.2.5 on 2021-08-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteAccessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dhcp_enabled', models.BooleanField(verbose_name='DHCP Disabled')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('port', models.IntegerField(verbose_name='Port')),
                ('subnet_mask', models.GenericIPAddressField(verbose_name='Subnet Mask')),
                ('broadcast_address', models.GenericIPAddressField(verbose_name='Broadcast Address')),
                ('gateway_address', models.GenericIPAddressField(verbose_name='Gateway Address')),
                ('dns_address', models.GenericIPAddressField(verbose_name='DNS Address')),
                ('dhcp_address', models.GenericIPAddressField(verbose_name='DHCP Address')),
            ],
        ),
    ]
