# Generated by Django 3.2.5 on 2021-08-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalAccessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baud_rate', models.IntegerField(verbose_name='Baud Rate')),
                ('data_bits', models.IntegerField(verbose_name='Data Bits')),
                ('stop_bits', models.IntegerField(verbose_name='Stop Bits')),
                ('parity', models.TextField(verbose_name='Parity Field')),
            ],
        ),
    ]
