# Generated by Django 3.2.5 on 2021-08-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_localaccesssettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localaccesssettings',
            name='parity',
            field=models.CharField(max_length=50, verbose_name='Parity Field'),
        ),
    ]
