# Generated by Django 3.2.5 on 2021-08-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_localaccesssettings_parity'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_ntp', models.BooleanField(verbose_name='Use NTP')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('server1', models.CharField(max_length=200, verbose_name='Server 1')),
                ('ip_address1', models.CharField(max_length=15, verbose_name='IP Address 1')),
                ('timezone1', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default=0, max_length=2, verbose_name='Timezone 1')),
                ('server2', models.CharField(max_length=200, verbose_name='Server 2')),
                ('ip_address2', models.CharField(max_length=15, verbose_name='IP Address 2')),
                ('timezone2', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24')], default=0, max_length=2, verbose_name='Timezone 2')),
            ],
        ),
    ]
