# Generated by Django 3.2.8 on 2021-10-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_localaccesssettings_open_cli'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesettings',
            name='ip_address1',
        ),
        migrations.RemoveField(
            model_name='timesettings',
            name='ip_address2',
        ),
        migrations.RemoveField(
            model_name='timesettings',
            name='timezone1',
        ),
    ]
