# Generated by Django 3.2.8 on 2021-10-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_auto_20211017_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteaccesssettings',
            name='open_remote',
            field=models.BooleanField(default=None, null=True, verbose_name='Remote Access Enabled'),
        ),
    ]
