# Generated by Django 3.2.8 on 2021-10-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_alter_remoteaccesssettings_open_remote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteaccesssettings',
            name='open_remote',
            field=models.BooleanField(default=None, verbose_name='Enable Remote Access'),
        ),
    ]
