# Generated by Django 3.2.5 on 2021-08-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='log_records',
            field=models.CharField(default=None, max_length=50, verbose_name='Log Dump'),
        ),
        migrations.AddField(
            model_name='log',
            name='type',
            field=models.CharField(default=None, max_length=25, verbose_name='Source Type'),
        ),
    ]
