# Generated by Django 3.2.5 on 2021-08-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_articles', '0002_auto_20210804_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=2, verbose_name='Language (like TR or EN)')),
                ('title', models.CharField(max_length=25, verbose_name='Remote Access Settings')),
                ('dhcp', models.CharField(max_length=40, verbose_name='DHCP Enabled/Disabled')),
                ('ip_address', models.CharField(max_length=30, verbose_name='IP Address')),
                ('port', models.CharField(max_length=25, verbose_name='Port')),
                ('subnet_mask', models.CharField(max_length=25, verbose_name='Subnet Mask')),
                ('broadcast_address', models.CharField(max_length=30, verbose_name='Broadcast Address')),
                ('gateway_address', models.CharField(max_length=25, verbose_name='Gateway Address')),
                ('dns_address', models.CharField(max_length=25, verbose_name='DNS Address')),
                ('dhcp_address', models.CharField(max_length=25, verbose_name='DHCP Address')),
                ('save', models.CharField(max_length=25, verbose_name='Save')),
                ('enabled', models.CharField(max_length=15, verbose_name='Enabled')),
                ('disabled', models.CharField(max_length=25, verbose_name='Disabled')),
            ],
        ),
        migrations.AlterField(
            model_name='log',
            name='lang',
            field=models.CharField(max_length=2, verbose_name='Language (like TR or EN)'),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_records',
            field=models.CharField(default=None, max_length=50, verbose_name='Log Dump Settings'),
        ),
    ]
