# Generated by Django 3.2.5 on 2021-08-05 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_articles', '0006_auto_20210806_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localaccessarticles',
            old_name='dhcp',
            new_name='baud_rate',
        ),
        migrations.RenameField(
            model_name='localaccessarticles',
            old_name='ip_address',
            new_name='data_bits',
        ),
        migrations.RenameField(
            model_name='localaccessarticles',
            old_name='subnet_mask',
            new_name='parity_text',
        ),
        migrations.RenameField(
            model_name='localaccessarticles',
            old_name='port',
            new_name='stop_bits',
        ),
    ]
