# Generated by Django 3.2.5 on 2021-08-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_articles', '0008_timesettingsarticles'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=2, verbose_name='Language (like TR or EN)')),
                ('user_administration', models.CharField(max_length=35, verbose_name='User Administration (page title)')),
                ('user_create_title', models.CharField(max_length=35, verbose_name='User Create (title)')),
                ('user_name_surname', models.CharField(max_length=35, verbose_name='Name Surname (field)')),
                ('username', models.CharField(max_length=25, verbose_name='Username (field)')),
                ('password', models.CharField(max_length=25, verbose_name='Password (field)')),
                ('confirm_password', models.CharField(max_length=30, verbose_name='Confirm Password (field)')),
                ('authority_status', models.CharField(max_length=25, verbose_name='Authority Status (field)')),
                ('create_user', models.CharField(max_length=25, verbose_name='Create (text)')),
                ('user_settings', models.CharField(max_length=35, verbose_name='User Settings (title)')),
                ('delete', models.CharField(max_length=20, verbose_name='Delete (field)')),
            ],
        ),
        migrations.AlterField(
            model_name='timesettingsarticles',
            name='date_time_field',
            field=models.CharField(max_length=25, verbose_name='Date and Time (field)'),
        ),
        migrations.AlterField(
            model_name='timesettingsarticles',
            name='timezone',
            field=models.CharField(max_length=25, verbose_name='Timezone (field)'),
        ),
    ]
