# Generated by Django 3.2.5 on 2021-08-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_articles', '0009_auto_20210806_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarFooterArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=2, verbose_name='Language (like TR or EN)')),
                ('homepage', models.CharField(max_length=20, verbose_name='Home (link)')),
                ('system_status', models.CharField(max_length=30, verbose_name='System Status (dropdown)')),
                ('statistics_field', models.CharField(max_length=20, verbose_name='Statistics (field)')),
                ('sensors', models.CharField(max_length=20, verbose_name='Sensors (field)')),
                ('log_records', models.CharField(max_length=30, verbose_name='Log Records (field)')),
                ('system_settings', models.CharField(max_length=30, verbose_name='System Settings (dropdown)')),
                ('remote_access_settings', models.CharField(max_length=35, verbose_name='Remote Access Settings (field)')),
                ('cli_access_settings', models.CharField(max_length=35, verbose_name='CLI Access Settings (field)')),
                ('time_settings', models.CharField(max_length=35, verbose_name='Time Settings (field)')),
                ('user_settings', models.CharField(max_length=35, verbose_name='User Settings (dropdown)')),
                ('user_administration', models.CharField(max_length=30, verbose_name='User Administration (field)')),
                ('authorization', models.CharField(max_length=35, verbose_name='Authorization (field)')),
                ('password_changing', models.CharField(max_length=35, verbose_name='Password Changing (field)')),
                ('logout_link', models.CharField(max_length=20, verbose_name='Logout (link)')),
                ('footer', models.CharField(max_length=35, verbose_name='All Rights Reserved (text)')),
            ],
        ),
    ]
