# Generated by Django 3.2.6 on 2021-09-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_articles', '0013_auto_20210912_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarfooterarticles',
            name='ftp_settings',
            field=models.CharField(default=None, max_length=15, null=True, verbose_name='FTP Settings (field)'),
        ),
        migrations.AlterField(
            model_name='navbarfooterarticles',
            name='input_settings',
            field=models.CharField(default=None, max_length=18, null=True, verbose_name='Input Settings (field)'),
        ),
        migrations.AlterField(
            model_name='navbarfooterarticles',
            name='video_transfer',
            field=models.CharField(default=None, max_length=35, null=True, verbose_name='Video Transfer Settings (dropdown)'),
        ),
        migrations.AlterField(
            model_name='navbarfooterarticles',
            name='video_transfer_settings',
            field=models.CharField(default=None, max_length=15, null=True, verbose_name='Settings (field)'),
        ),
    ]
