# Generated by Django 3.2.6 on 2021-10-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_articles', '0014_auto_20210912_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacketsTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=2, verbose_name='Language (like TR or EN)')),
                ('management_port_incoming', models.CharField(max_length=20, verbose_name='Management Port Incoming (title)')),
                ('management_port_outgoing', models.CharField(max_length=20, verbose_name='Management Port Outgoing (title)')),
                ('one_way_port_incoming', models.CharField(max_length=20, verbose_name='One Way Port Incoming (title)')),
                ('one_way_port_outgoing', models.CharField(max_length=20, verbose_name='One Way Port Outgoing (title)')),
            ],
        ),
    ]
