# Generated by Django 3.2.6 on 2021-10-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_articles', '0015_packetstitles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packetstitles',
            name='management_port_incoming',
            field=models.CharField(max_length=30, verbose_name='Management Port Incoming (title)'),
        ),
        migrations.AlterField(
            model_name='packetstitles',
            name='management_port_outgoing',
            field=models.CharField(max_length=30, verbose_name='Management Port Outgoing (title)'),
        ),
        migrations.AlterField(
            model_name='packetstitles',
            name='one_way_port_incoming',
            field=models.CharField(max_length=30, verbose_name='One Way Port Incoming (title)'),
        ),
        migrations.AlterField(
            model_name='packetstitles',
            name='one_way_port_outgoing',
            field=models.CharField(max_length=30, verbose_name='One Way Port Outgoing (title)'),
        ),
    ]
