# Generated by Django 3.2.6 on 2021-10-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_articles', '0016_auto_20211003_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='localaccessarticles',
            name='open_cli_access_info_text',
            field=models.CharField(default=None, max_length=55, verbose_name='Open CLI Access (info text)'),
        ),
        migrations.AddField(
            model_name='localaccessarticles',
            name='open_cli_access_switch',
            field=models.CharField(default=None, max_length=20, verbose_name='Open CLI Access (switch)'),
        ),
    ]
