# Generated by Django 3.2.6 on 2021-10-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_articles', '0017_auto_20211003_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localaccessarticles',
            name='open_cli_access_info_text',
            field=models.CharField(default=None, max_length=70, verbose_name='Open CLI Access (info text)'),
        ),
    ]
