# Generated by Django 3.2.8 on 2021-10-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_articles', '0018_alter_localaccessarticles_open_cli_access_info_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteaccessarticles',
            name='open_remote',
            field=models.CharField(default=None, max_length=25, null=True, verbose_name='Open Remote Access'),
        ),
    ]
