# Generated by Django 3.2.8 on 2021-10-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_articles', '0020_alter_remoteaccessarticles_open_remote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=2, verbose_name='Language (like TR or EN)')),
                ('transmitter_temprature', models.CharField(max_length=50, verbose_name='Transmitter Temprature')),
                ('reciever_temprature', models.CharField(max_length=50, verbose_name='Reciever Temprature')),
                ('case_sensor', models.CharField(max_length=30, verbose_name='Case Sensor')),
            ],
        ),
    ]
