# Generated by Django 3.2.8 on 2021-10-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_articles', '0021_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarfooterarticles',
            name='packets',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='Packets (field)'),
        ),
    ]
