# Generated by Django 3.2.8 on 2021-10-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_articles', '0023_auto_20211030_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticsarticle',
            name='now',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='Usage'),
        ),
    ]
