# Generated by Django 3.2.8 on 2021-11-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_articles', '0025_authorization'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=2, verbose_name='Language (like TR or EN)')),
                ('title', models.CharField(max_length=25, verbose_name='Title')),
                ('go', models.CharField(max_length=10, verbose_name='Go')),
                ('edit', models.CharField(max_length=10, verbose_name='Edit')),
                ('authority_content', models.CharField(max_length=20, verbose_name='Authority Content')),
                ('access', models.CharField(max_length=10, verbose_name='Access')),
                ('change', models.CharField(max_length=10, verbose_name='Change')),
            ],
        ),
        migrations.DeleteModel(
            name='Authorization',
        ),
    ]
