# Generated by Django 3.2.8 on 2021-11-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_articles', '0026_auto_20211102_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthorization',
            name='page_title',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='Authorization'),
        ),
    ]
