# Generated by Django 3.2.8 on 2021-11-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_articles', '0027_userauthorization_page_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthorization',
            name='page_title',
            field=models.CharField(default=None, max_length=20, verbose_name='Authorization'),
        ),
    ]
