# Generated by Django 3.2.8 on 2021-11-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=10, verbose_name='User Type (admin/operator/superadmin')),
                ('user_administration', models.BooleanField(verbose_name='User Administration')),
            ],
        ),
    ]
