# Generated by Django 3.2.8 on 2021-11-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211102_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorization',
            name='user_administration_access',
            field=models.BooleanField(default=None, verbose_name='User Administration Access'),
        ),
        migrations.AlterField(
            model_name='authorization',
            name='user_administration_change',
            field=models.BooleanField(default=None, verbose_name='User Administration Change'),
        ),
    ]
