# Generated by Django 3.2.5 on 2021-08-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_top', models.IntegerField(verbose_name='Memory Top')),
                ('memory_now', models.IntegerField(verbose_name='Memory Now')),
                ('cpu_top', models.IntegerField(verbose_name='CPU Top')),
                ('cpu_now', models.IntegerField(verbose_name='CPU Now')),
                ('ssd_top', models.IntegerField(verbose_name='SSD Top')),
                ('ssd_now', models.IntegerField(verbose_name='SSD Now')),
                ('packet_count', models.IntegerField(verbose_name='Packet Count')),
            ],
        ),
    ]
