# Generated by Django 3.2.5 on 2021-08-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_statics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statics',
            name='memory_now',
            field=models.FloatField(verbose_name='Memory Now'),
        ),
        migrations.AlterField(
            model_name='statics',
            name='memory_top',
            field=models.FloatField(verbose_name='Memory Top'),
        ),
    ]
