# Generated by Django 3.2.6 on 2021-10-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_auto_20210807_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_port_incoming', models.IntegerField(verbose_name='Management Port Incoming')),
                ('management_port_outgoing', models.IntegerField(verbose_name='Management Port Outgoing')),
                ('one_way_port_incoming', models.IntegerField(verbose_name='One Way Port Incoming')),
                ('one_way_port_outgoing', models.IntegerField(verbose_name='One Way Port Ourgoing')),
            ],
        ),
        migrations.RemoveField(
            model_name='statics',
            name='packet_count',
        ),
    ]
