# Generated by Django 3.2.8 on 2021-10-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_auto_20211003_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_temprature', models.FloatField(verbose_name='Data Temprature')),
                ('area_temprature', models.FloatField(verbose_name='Area Temprature')),
                ('case_sensor', models.BooleanField(verbose_name='Case Sensor')),
            ],
        ),
    ]
