# Generated by Django 3.2.8 on 2021-10-23 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0006_sensors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensors',
            old_name='area_temprature',
            new_name='reciever_temprature',
        ),
    ]
