# Generated by Django 3.2.6 on 2021-08-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udp_comm_ip_address', models.GenericIPAddressField(verbose_name='udp_comm_ip_address')),
                ('udp_comm_port', models.IntegerField(verbose_name='udp_comm_port')),
                ('video_frame_rate', models.IntegerField(verbose_name='video_frame_rate (fps)')),
                ('video_codec_type', models.CharField(choices=[('flv', 'flv'), ('avi', 'avi'), ('hls', 'hls'), ('ogg', 'ogg'), ('mpeg4', 'mpeg4'), ('gif', 'gif'), ('jpeg2000', 'jpeg2000'), ('vpx', 'vpx'), ('h264', 'h264'), ('h265', 'h265'), ('avs2', 'avs2')], max_length=10, verbose_name='video_codec_type')),
            ],
        ),
    ]
