# Generated by Django 3.2.6 on 2021-08-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='video_codec_type',
            field=models.CharField(choices=[('0', 'flv'), ('1', 'avi'), ('2', 'hls'), ('3', 'ogg'), ('4', 'mpeg4'), ('5', 'gif'), ('6', 'jpeg2000'), ('7', 'vpx'), ('8', 'h264'), ('9', 'h265'), ('10', 'avs2')], max_length=10, verbose_name='video_codec_type'),
        ),
    ]
