# Generated by Django 3.2.6 on 2021-09-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_transfer', '0004_alter_generalsettings_video_codec_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_protocol', models.CharField(choices=[('0', 'rtsp'), ('1', 'rtp'), ('2', 'rtmp'), ('3', 'mpeg'), ('4', 'srt'), ('5', 'hls')], max_length=15, verbose_name='input_protocol')),
                ('input_url', models.URLField(max_length=30, verbose_name='input_url')),
            ],
        ),
    ]
