# Generated by Django 3.2.6 on 2021-09-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_transfer', '0005_inputsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputsettings',
            name='input_url',
            field=models.CharField(max_length=30, verbose_name='input_url'),
        ),
    ]
