# Generated by Django 3.2.6 on 2021-09-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_transfer', '0007_auto_20210901_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputsettings',
            name='output_audio_format',
            field=models.CharField(choices=[('0', 'vpx'), ('1', 'h264'), ('2', 'h265'), ('3', 'avs2')], max_length=5, verbose_name='output_audio_format'),
        ),
        migrations.AlterField(
            model_name='outputsettings',
            name='output_video_format',
            field=models.CharField(choices=[('0', 'flv'), ('1', 'avi'), ('2', 'hls'), ('3', 'ogg'), ('4', 'mpeg4'), ('5', 'gif'), ('6', 'jpeg2000')], max_length=9, verbose_name='output_video_format'),
        ),
    ]
